services:
  db:
    image: postgres:15-alpine
    container_name: potrotitulate_db
    environment:
      - POSTGRES_DB=potrotitulate
      - POSTGRES_USER=potroadmin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432" # Expone el puerto por si quieres conectar un cliente de BD desde tu PC

  web:
    container_name: potrotitulate_web
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app # <-- Mantiene el backend sincronizado
      - ./FrontEnd:/frontend # <-- ¡AÑADE ESTA LÍNEA! Mapea el frontend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=potrotitulate
      - DB_USER=potroadmin
      - DB_PASS=admin
      - SECRET_KEY=${SECRET_KEY} # Lee la secret key desde un archivo .env
      - DEBUG=1
    depends_on:
      - db

volumes:
  postgres_data: