services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/staticfiles:/PotroTitulate/staticfiles
      - ./backend/media:/PotroTitulate/media

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./backend/staticfiles:/staticfiles
      - ./backend/media:/mediafiles
      - ./frontend/dist:/usr/share/nginx/html/frontend
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
