# Generated by Django 5.1.4 on 2025-01-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativos',
            fields=[
                ('id_administrativo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'administrativos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('fecha_subida', models.DateField()),
                ('estado_validacion', models.CharField(max_length=50)),
                ('comentarios_validacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateField()),
                ('estado_lectura', models.BooleanField()),
            ],
            options={
                'db_table': 'notificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpcionTitulacion',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_opcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'opcion_titulacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaSeguridad',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('ultimo_acceso', models.DateField()),
                ('ip_acceso', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sistema_seguridad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sustentante',
            fields=[
                ('id_sustentante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=15, unique=True)),
                ('correo_electronico', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sustentante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id_tramite', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_titulacion', models.TextField()),
                ('estado_actual', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
            ],
            options={
                'db_table': 'tramites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SistemaAlmacenamiento',
            fields=[
                ('id_documento', models.OneToOneField(db_column='id_documento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.documentos')),
                ('ruta_archivo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sistema_almacenamiento',
                'managed': False,
            },
        ),
    ]
