# Generated by Django 5.1.4 on 2025-09-19 22:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('fecha_subida', models.DateField(default=django.utils.timezone.now)),
                ('estado_validacion', models.CharField(max_length=50)),
                ('comentarios_validacion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='SistemaSeguridad',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('ultimo_acceso', models.DateField()),
                ('ip_acceso', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sistema_seguridad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sustentante',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_sustentante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=15, unique=True)),
                ('correo_electronico', models.EmailField(max_length=100, unique=True)),
                ('contrasena_temporal', models.BooleanField(default=False)),
                ('licenciatura', models.CharField(choices=[('Administracion', 'Administración'), ('Contaduria', 'Contaduría'), ('Mercadotecnia', 'Mercadotecnia'), ('Informatica_Administrativa', 'Informática Administrativa')], max_length=100)),
                ('confirmado', models.BooleanField(default=False)),
                ('oportunidades_restantes', models.IntegerField(default=3)),
                ('periodo_ingreso', models.CharField(max_length=5)),
                ('periodo_egreso', models.CharField(max_length=5)),
                ('es_escuela_incorporada', models.BooleanField(default=False)),
                ('escuela_de_procedencia', models.CharField(blank=True, max_length=100, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Sustentante',
                'verbose_name_plural': 'Sustentantes',
                'db_table': 'sustentante',
            },
        ),
        migrations.CreateModel(
            name='Formatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='formatos/')),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionTitulacion',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_opcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Opción de Titulación',
                'verbose_name_plural': 'Opciones de Titulación',
                'db_table': 'opcion_titulacion',
            },
        ),
        migrations.CreateModel(
            name='PreguntasFrecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500)),
                ('respuesta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SistemaAlmacenamiento',
            fields=[
                ('id_documento', models.OneToOneField(db_column='id_documento', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.documentos')),
                ('ruta_archivo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sistema_almacenamiento',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='documentos',
            name='id_sustentante',
            field=models.ForeignKey(db_column='id_sustentante', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentos',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Administrativos',
            fields=[
                ('id_administrativo', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_administrativo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrativo',
                'verbose_name_plural': 'Administrativos',
                'db_table': 'administrativos',
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateField(default=django.utils.timezone.now)),
                ('estado_lectura', models.BooleanField(default=False)),
                ('es_de_administrador', models.BooleanField(default=False)),
                ('id_administrativo', models.ForeignKey(db_column='id_administrativo', on_delete=django.db.models.deletion.CASCADE, to='api.administrativos')),
                ('id_sustentante', models.ForeignKey(db_column='id_sustentante', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
        migrations.AddField(
            model_name='sustentante',
            name='id_opcion',
            field=models.ForeignKey(blank=True, db_column='id_opcion', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.opciontitulacion'),
        ),
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id_tramite', models.AutoField(primary_key=True, serialize=False)),
                ('estado_actual', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
                ('aprobado', models.BooleanField(default=False)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_opcion', models.ForeignKey(db_column='id_opcion', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.opciontitulacion')),
                ('id_sustentante', models.ForeignKey(db_column='id_sustentante', on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to=settings.AUTH_USER_MODEL)),
                ('rechazado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites_rechazados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tramites',
            },
        ),
        migrations.CreateModel(
            name='HistorialTramite',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('detalles', models.TextField()),
                ('fecha_accion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='api.tramites')),
            ],
            options={
                'db_table': 'historial_tramites',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.AddField(
            model_name='documentos',
            name='id_tramite',
            field=models.ForeignKey(blank=True, db_column='id_tramite', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tramites'),
        ),
    ]
