# Generated by Django 5.1.4 on 2025-01-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sustentante',
            fields=[
                ('id_sustentante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=15, unique=True)),
                ('correo_electronico', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('opcion_titulacion', models.CharField(max_length=100)),
            ],
        ),
    ]
