# Generated by Django 5.1.4 on 2025-01-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sustentante',
            old_name='apellido',
            new_name='apellidos',
        ),
    ]
