# Generated by Django 5.1.4 on 2025-08-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_documentos_historialtramite_notificaciones_and_more'),
    ]

    operations = [
    ]
