# Generated by Django 5.1.4 on 2025-02-06 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tramites_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramites',
            name='ruta_titulacion',
        ),
        migrations.AddField(
            model_name='tramites',
            name='id_opcion',
            field=models.ForeignKey(db_column='id_opcion', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.opciontitulacion'),
        ),

    ]
