# Generated by Django 5.1.4 on 2025-08-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
    ]
