# Generated by Django 5.1.4 on 2025-02-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_tramites_ruta_titulacion_tramites_id_opcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramites',
            options={'managed': False},
        ),
    ]
