# Generated by Django 5.1.4 on 2025-02-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tramites_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentos',
            options={'managed': True},
        ),
    ]
