# Generated by Django 5.1.4 on 2025-02-14 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_documentos_options_documentos_archivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentos',
            options={'managed': True},
        ),
    ]
