# Generated by Django 5.1.4 on 2025-02-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_documentos_options_documentos_id_sustentante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentos',
            options={'managed': False},
        ),
    ]
