# Generated by Django 5.1.4 on 2025-03-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_documentos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sustentante',
            options={},
        ),
    ]
