# Generated by Django 5.1.4 on 2025-03-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_sustentante_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sustentante',
            name='contrasena',
        ),
        migrations.AddField(
            model_name='sustentante',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sustentante',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='sustentantes_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='sustentante',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sustentante',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sustentante',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='sustentante',
            name='password',
            field=models.CharField(default='password123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sustentante',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='sustentantes_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='sustentante',
            name='correo_electronico',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
