# Generated by Django 5.1.4 on 2025-03-13 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_sustentante_contrasena_sustentante_confirmado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustentante',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
