# Generated by Django 5.1.4 on 2025-03-27 01:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sustentante_contrasena_temporal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tramites',
            options={},
        ),
        
        migrations.CreateModel(
            name='HistorialTramite',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('detalles', models.TextField()),
                ('fecha_accion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='api.tramites')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Trámite',
                'verbose_name_plural': 'Historial de Trámites',
                'db_table': 'historial_tramites',
                'ordering': ['-fecha_accion'],
            },
        ),
    ]
