# Generated by Django 5.1.4 on 2025-03-27 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_documentos_options_alter_tramites_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='historialtramite',
            options={'managed': False, 'ordering': ['-fecha_accion'], 'verbose_name': 'Historial de Trámite', 'verbose_name_plural': 'Historial de Trámites'},
        ),
        migrations.AlterModelOptions(
            name='tramites',
            options={'managed': False},
        ),
       
    ]
